name: deploy and configure
on: [push]
jobs:
  local:
    runs-on: Linux
    steps:
      - name: Run it
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          options: --inventory host
