name: deploy and configure
on: [push]
jobs:
  Deploy:
    runs-on: Linux
    steps:
      - name: Dir
        run: pwd
      - name: Run playbook 
        run: ansible-playbook -i localhost test/deploy.yml 
